"use client";

import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-purple-50 to-white dark:from-purple-950 dark:to-slate-900">
      <Navbar />

      <main className="flex-1 container mx-auto px-4 py-12 max-w-3xl">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-purple-600 hover:text-purple-800 dark:text-purple-400 dark:hover:text-purple-200 mb-8 text-sm font-medium transition-colors"
        >
          ← Back to Home
        </Link>

        <h1 className="text-3xl md:text-4xl font-bold bg-gradient-to-r from-purple-600 to-violet-500 bg-clip-text text-transparent mb-8">
          Terms of Service
        </h1>

        <p className="text-sm text-slate-500 dark:text-slate-400 mb-8">
          Last updated: February 28, 2026
        </p>

        <div className="space-y-6 text-slate-700 dark:text-slate-300">
          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              1. Acceptance of Terms
            </h2>
            <p className="leading-relaxed">
              By accessing or using NarrVoca, you agree to be bound by these Terms of Service. If you do
              not agree to these terms, please do not use the application.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              2. Use of the Service
            </h2>
            <p className="leading-relaxed">
              NarrVoca is provided for educational purposes. You agree to:
            </p>
            <ul className="mt-2 space-y-1 list-disc list-inside ml-2">
              <li>Use the service only for lawful, personal language-learning purposes.</li>
              <li>Not attempt to reverse-engineer, scrape, or abuse the platform.</li>
              <li>Not share your account credentials with others.</li>
              <li>Provide accurate information when creating an account.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              3. User Content
            </h2>
            <p className="leading-relaxed">
              Your written responses to story checkpoints are used solely to evaluate your learning
              progress via our LLM grading system. We do not claim ownership of your responses and
              do not share them with third parties beyond the grading pipeline described in our
              Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              4. Intellectual Property
            </h2>
            <p className="leading-relaxed">
              All story content, UI elements, and NarrVoca branding are the intellectual property of
              the NarrVoca team. The underlying Vocora platform retains its original copyright. Story
              content generated by AI is provided for educational use only.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              5. Disclaimer of Warranties
            </h2>
            <p className="leading-relaxed">
              NarrVoca is provided "as is" without warranties of any kind. Language grading is performed
              by an AI model and may not be perfectly accurate. We do not guarantee that the service will
              be uninterrupted or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              6. Changes to Terms
            </h2>
            <p className="leading-relaxed">
              We may update these terms from time to time. Continued use of the service after changes
              constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-300 mb-3">
              7. Contact
            </h2>
            <p className="leading-relaxed">
              For questions about these terms, please visit our{" "}
              <Link
                href="/contact"
                className="text-purple-600 hover:text-purple-800 dark:text-purple-400 dark:hover:text-purple-200 underline"
              >
                contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
