const termsTranslations = {
  en: {
    backToHome: "← Back to Home",
    heading: "Terms of Service",
    lastUpdated: "Last updated: February 28, 2026",
    s1: {
      title: "1. Acceptance of Terms",
      body: "By accessing or using NarrVoca, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the application.",
    },
    s2: {
      title: "2. Use of the Service",
      body: "NarrVoca is provided for educational purposes. You agree to:",
      items: [
        "Use the service only for lawful, personal language-learning purposes.",
        "Not attempt to reverse-engineer, scrape, or abuse the platform.",
        "Not share your account credentials with others.",
        "Provide accurate information when creating an account.",
      ],
    },
    s3: {
      title: "3. User Content",
      body: "Your written responses to story checkpoints are used solely to evaluate your learning progress via our LLM grading system. We do not claim ownership of your responses and do not share them with third parties beyond the grading pipeline described in our Privacy Policy.",
    },
    s4: {
      title: "4. Intellectual Property",
      body: "All story content, UI elements, and NarrVoca branding are the intellectual property of the NarrVoca team. The underlying Vocora platform retains its original copyright. Story content generated by AI is provided for educational use only.",
    },
    s5: {
      title: "5. Disclaimer of Warranties",
      body: 'NarrVoca is provided "as is" without warranties of any kind. Language grading is performed by an AI model and may not be perfectly accurate. We do not guarantee that the service will be uninterrupted or error-free.',
    },
    s6: {
      title: "6. Changes to Terms",
      body: "We may update these terms from time to time. Continued use of the service after changes constitutes your acceptance of the updated terms.",
    },
    s7: {
      title: "7. Contact",
      body: "For questions about these terms, please visit our",
      link: "contact page",
    },
  },
  es: {
    backToHome: "← Volver al inicio",
    heading: "Términos de Servicio",
    lastUpdated: "Última actualización: 28 de febrero de 2026",
    s1: {
      title: "1. Aceptación de los Términos",
      body: "Al acceder o usar NarrVoca, aceptas estar sujeto a estos Términos de Servicio. Si no estás de acuerdo con estos términos, por favor no utilices la aplicación.",
    },
    s2: {
      title: "2. Uso del Servicio",
      body: "NarrVoca se proporciona con fines educativos. Aceptas:",
      items: [
        "Usar el servicio solo para fines legales y personales de aprendizaje de idiomas.",
        "No intentar realizar ingeniería inversa, raspar datos ni abusar de la plataforma.",
        "No compartir tus credenciales de cuenta con otras personas.",
        "Proporcionar información precisa al crear una cuenta.",
      ],
    },
    s3: {
      title: "3. Contenido del Usuario",
      body: "Tus respuestas escritas a los puntos de control de las historias se utilizan únicamente para evaluar tu progreso de aprendizaje a través de nuestro sistema de calificación por IA. No reclamamos la propiedad de tus respuestas y no las compartimos con terceros más allá del proceso de calificación descrito en nuestra Política de Privacidad.",
    },
    s4: {
      title: "4. Propiedad Intelectual",
      body: "Todo el contenido de las historias, los elementos de la interfaz y la marca NarrVoca son propiedad intelectual del equipo de NarrVoca. La plataforma Vocora subyacente conserva su copyright original. El contenido de las historias generado por IA se proporciona únicamente con fines educativos.",
    },
    s5: {
      title: "5. Exclusión de Garantías",
      body: 'NarrVoca se proporciona "tal cual" sin garantías de ningún tipo. La calificación del idioma es realizada por un modelo de IA y puede no ser perfectamente precisa. No garantizamos que el servicio sea ininterrumpido o libre de errores.',
    },
    s6: {
      title: "6. Cambios en los Términos",
      body: "Podemos actualizar estos términos de vez en cuando. El uso continuado del servicio después de los cambios constituye tu aceptación de los términos actualizados.",
    },
    s7: {
      title: "7. Contacto",
      body: "Para preguntas sobre estos términos, visita nuestra",
      link: "página de contacto",
    },
  },
  zh: {
    backToHome: "← 返回首页",
    heading: "服务条款",
    lastUpdated: "最后更新：2026年2月28日",
    s1: {
      title: "1. 条款接受",
      body: "访问或使用 NarrVoca 即表示您同意受这些服务条款的约束。如果您不同意这些条款，请不要使用本应用程序。",
    },
    s2: {
      title: "2. 服务使用",
      body: "NarrVoca 仅用于教育目的。您同意：",
      items: [
        "仅将本服务用于合法的个人语言学习目的。",
        "不得尝试对平台进行逆向工程、抓取数据或滥用平台。",
        "不得与他人共享您的账户凭据。",
        "创建账户时提供准确信息。",
      ],
    },
    s3: {
      title: "3. 用户内容",
      body: "您对故事检查点的书面回答仅用于通过我们的 AI 评分系统评估您的学习进度。我们不主张对您的回答拥有所有权，也不会在我们隐私政策中描述的评分流程之外与第三方共享这些回答。",
    },
    s4: {
      title: "4. 知识产权",
      body: "所有故事内容、界面元素和 NarrVoca 品牌均为 NarrVoca 团队的知识产权。底层 Vocora 平台保留其原始版权。AI 生成的故事内容仅供教育使用。",
    },
    s5: {
      title: "5. 免责声明",
      body: 'NarrVoca 按"现状"提供，不提供任何形式的保证。语言评分由 AI 模型执行，可能不完全准确。我们不保证服务不会中断或不出现错误。',
    },
    s6: {
      title: "6. 条款变更",
      body: "我们可能会不时更新这些条款。变更后继续使用本服务即表示您接受更新后的条款。",
    },
    s7: {
      title: "7. 联系方式",
      body: "如对这些条款有疑问，请访问我们的",
      link: "联系页面",
    },
  },
} as const;

export default termsTranslations;
